<html>
<head>
	
	<meta http-equiv="Content-Type" content="text/html" charset="utf-8" />
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl('assests/css/bootstrap.min.css')); ?>
	<?php echo $this->headScript()->appendFile($this->baseUrl('assests/js/bootstrap.min.js')); ?>

</head>

<body>
	
	<legend> 
		Agenda de contatos
		<a href="create" class="btn btn-info btn-small">Add Contato</a>
	</legend>
	
	<?php echo $this->layout()->content; ?>

</body>

</html>